// Generated by CoffeeScript 1.3.3
(function() {

  $(window).ready(function() {
    var $targets;
    $targets = $('img[src$="svg"]').hide();
    return $targets.each(function() {
      var _this = this;
      return $.get(this.src, function(data) {
        var $d, attr;
        $d = $(data).find('svg');
        attr = _this.attributes;
        $.extend(attr, $d[0].attributes);
        $(attr).each(function() {
          var nName, nValue;
          nName = this.nodeName;
          nValue = this.nodeValue;
          if (nName !== 'src' && nName !== 'style') {
            return $d.attr(nName, nValue);
          }
        });
        return $(_this).replaceWith($d);
      });
    });
  });

}).call(this);
